version: '3.8'
services:
    # PHP + Apache Service
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
        networks:
            - laravel_network
        environment:
            - DB_CONNECTION=pgsql
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}

# Networks
networks:
    laravel_network:
        driver: bridge
